name: Build Docker Image
permissions:
  packages: write
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ghcr.io/maa123/gen-image-proxy:latest,ghcr.io/maa123/gen-image-proxy:${{ github.sha }}
          cache-from: type=gha,scope=gen-image-proxy
          cache-to: type=gha,mode=max,scope=gen-image-proxy
