name: Rust Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            index.crates.io:443
            static.crates.io:443
            static.rust-lang.org:443
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --no-self-update
          rustup default stable

      - name: Generate lockfile hash
        run: echo "CARGO_LOCK_HASH=$(sha256sum Cargo.lock | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Cache cargo registry
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ env.CARGO_LOCK_HASH }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
